package io.github.alexandrepiveteau.echo.internal.history

/**
 * A [PersistentHistory] represents a persistent data structure which has a [current] value and can
 * receive some events [T] to increment the [current] state.
 *
 * @param T the type of the events.
 * @param M the type of the [current] value.
 * @param R the type of [forward] meta-data.
 */
internal interface PersistentHistory<out T, out M, out R> {

  /** The current aggregated value for the history. */
  val current: M

  /**
   * Incrementally aggregates the given [event] and returns a new [Pair] of [PersistentHistory] and
   * the meta-data generated by the [forward] event insertion.
   */
  fun forward(event: @UnsafeVariance T): Pair<PersistentHistory<T, M, R>, R>
}
